
Resources:
  CFMmaven:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      InstanceType: t2.micro
      ImageId: ami-007855ac798b5175e
      KeyName: manishImpressico-KP
      SecurityGroups:
       - manishImpressico-SG
      Tags:
        - Key: Name
          Value: manish-task2-slave
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo apt update
         
