Parameters:
  AvailabiliZones:
    Type: String
    Description: Can be found on top right side of Screen.
    Default: us-east-1a
  
  TypeofInstance:
    Type: String
    Description: must be selected according to need.
    AllowedValues: 
      - t2.micro
      - t3.medium
    Default: t3.medium
    
  NameofInstance:
    Type: String
    Default: manish-master
    
  SecurityGroup:
    Type: String
    Default: manishImpressico-SG
    
  KeyPair:
    Type: String
    Default: manishImpressico-KP
    
  ImageId:
    Type: String
    Default: ami-007855ac798b5175e
    
Resources:
  CFMmaven:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: !Ref AvailabiliZones
      InstanceType: !Ref TypeofInstance
      ImageId: !Ref ImageId
      KeyName: !Ref KeyPair
      SecurityGroups:
       - !Ref SecurityGroup
       
      Tags:
        - Key: Name
          Value: !Ref NameofInstance
          
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          #installing jenkins
          apt update
          apt install awscli -y
          apt install openjdk-17-jdk -y
          curl -fsSL https://pkg.jenkins.io/debian/jenkins.io-2023.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null
          echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null
          apt-get update
          apt-get install jenkins -y